default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV['DATABASE_URL']%>
  encoding: utf8
  timeout: 5000

  
test:
  <<: *default
  url: <%= ENV['DATABASE_URL']%>
  encoding: unicode
  template: template0

production:
  <<: *default